export { default as useImageQuery } from "./imageQuery"
export { default as useHomePageQuery } from "./homePageQuery"
export { default as useCountryQuery } from "./countryQuery"
export { default as useDestinationQuery } from "./destinationQuery"
export { default as useActivityQuery } from "./activityQuery"
export { default as useFAQQuery } from "./faqQuery"
export { default as useHowItWorksQuery } from "./howItWorksQuery"
export { default as useReviewQuery } from "./reviewQuery"
export { default as useTeamQuery } from "./teamQuery"
export { default as useWildkiwiQuery } from "./wildkiwiQuery"
export { default as usePrivacyPolicyQuery } from "./privacyPolicyQuery"
export { useThemeRoutesConfigQuery } from "./themeRoutesConfigQuery"
export { useThemeMenuLabelQuery } from "./themeRoutesConfigQuery"
export { default as useThemeFooterQuery } from "./themeFooterQuery"
export { default as useThemeModalQuery } from "./themeModalQuery"
